### PR TITLE
Adds the Cyanide-class Interceptor

### PR DESCRIPTION
**Pull request by Dethstorm**
## About The Pull Request
Implements the SYN-C Cyanide-class Interceptor for the cheap price of 200 coins! Using a revamped model of an old SpaceRuin ship, the Interceptor is a pill-like ship, featuring limited equipment alongside limited space. It is bigger than a pill, and contains higher quality equipment, but it is a SYN-C ship so this should help the faction balance. As a unique feature of this ship, the Interceptor is able to undock from planets in an extremely short amount of time to allow for emergency take-offs. It includes 3 crewmembers, 1 Syndicate Captain and 2 Syndicate Marines (The cryobed is inside the SMES). 

It contains an SMES, a helm control console, a Syndicate Vendor, a PACMAN Uranium generator, an autolathe, wideband comms and two turrets. The equipment locker contains 3 Black and Red Space Suits and their respective Helmets, 3 double-extended oxygen tanks, 3 resonators, 3 manual mining scanners, 3 energy sabers, a full syndicate toolbox and a stack of cable coil. The fuel locker contains 10 uranium sheets for the PACMAN, use them carefully. 
WARNING: The Interceptor has wires inside its walls, it would otherwise be impossible to power this ship and keep it's unique style. You can set-up your engine prechargers from the outside of the ship.
Screenshot_1788
Screenshot_1789

## Why It's Good For The Game
I believe this should help balance the overwhelming amount of NEU ships, and lacking amount of faction ships while adding a new challenge for all the pill-lovers out there.

## Changelog
:cl:
add: Added cyanide.dmm to _maps/shuttles/shiptest/voidcrew
add: Added SYN-C_cyanide.json _maps/configs
update: Added SyndiVendor due to popular demand.
update: Fixed PACMAN generator, added three manual mining scanners.
update: Updated screenshots.
update: Increased price to 200 due to it having a literal syndivendor.
update: Added the expansion permit.
update: Added a holopad.
/:cl:

### CODE REVIEW

**Comment by theta006** [comment]
i say it needs guns to be a c type

**Comment by bsolomon9** [comment]
This is great but i THINK the port might be the wrong way at first glance
edit: my thinking was wrong it doesn't matter

**Comment by Jackriip** [comment]
The generator is non-existent, maybe check the typepath as I think they were modularized recently

**Comment by Dethstorm** [comment]
Added gun vendor due to popular demand, will check the generator thing.

**Comment by Dethstorm** [comment]
Fixed generator and added manual mining scanners. Seems to be ready unless there's any more feedback.
Edit: Typo

**Comment by bsolomon9** [comment]
Test merged

**Comment by githubuser4141** [comment]
Needs a blueprints scroll for expansion. Could a few picks or drills be placed in? Resonators can't dig sand and don't add mining skill. I like the concept though!

**Comment by Dethstorm** [comment]
> Needs a blueprints scroll for expansion. Could a few picks or drills be placed in? Resonators can't dig sand and don't add mining skill. I like the concept though!


Shovels are available through the autolathe, believe it or not a shovel can be used to dig. Resonators are often better against fauna, and since this ship is made for combat, I think it is better for it to spawn with these instead of pickaxes (and because people often forget about resonators). I will add the blueprint scroll shortly.

**Pull request merged**
