### PR TITLE
Removes Wright & Some capitalisation changes

### PR DESCRIPTION
**Pull request by ShibaInuLord**
## About The Pull Request
Removes the Wright and Tartarus as they are pretty unneeded in the current environment, with wright being literally useless except for ace attorney rp and tartarus being basically half empty space. 

## Why It's Good For The Game
Ship selection refinement good

### CODE REVIEW

**Comment by dwasint** [comment]
i can get behind the wright removal, but im not that sure on the tartarus. I see it quite often. Although that might be due to it being a starting ship.

**Comment by GuiltyNeko** [comment]
It's likely because it's a starter ship, because yes, it is a starter ship.

**Comment by ShibaInuLord** [comment]
Yep, Tartarus is a starter ship, and aside from that its rarely bought at all

**Comment by githubuser4141** [comment]
It's probably rarely bought because it's a starter ship and there's no reason to buy one when you can spawn in it for free. I don't get how a ship can be "unneeded", it's an interesting map that people play on, why remove people's options? There's also a lot of other ships, armor pieces, clothing which aren't used often, are we going to remove all ships except 1-5 commonly used ones? Why? Just because you don't enjoy it doesn't mean it should be taken away.

**Comment by NiftyRyanyan** [comment]
Make sure to remove all other ships designed around role playing, they might interrupt the other player’s team death match!

**Comment by dwasint** [comment]
from a ship stand point i can get behind the removal of the wright i can't say the same for the tartarus though.

**Comment by ShibaInuLord** [comment]
hmm, saw some complaints that tartarus was just half useless space as it has no atmos, but that can be fixed yeah so gonna remove that from this pr and maybe improve it idk

**Comment by ShibaInuLord** [comment]
> Make sure to remove all other ships designed around role playing, they might interrupt the other player’s team death match!

thank you for your valued opinion doing so now

**Comment by githubuser4141** [comment]
Here's the Wright for anyone wondering what it looks like. I don't get why or if it's disliked, it's not a combat ship but the aesthetic fits doing paperwork or DnD RP.

wright

**Comment by dwasint** [comment]
I'm gonna close this for now, after we rebase i'll take another look once we have a solid direction of what ships should look like

**Pull request closed without merging**
