### PR TITLE
Makes the twinkleshine's PML spawn with a magazine. 

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
I did a LOT to try to find a code solution to this. The answer is "whatever gives every magazine a full clip worth of ammo when it gets spawned needs to have a check added" or alternatively, "add an empty subtype to the PML's mag with nulled contents" but option one is hard and option two is bad. So we get a normal PML.

## Why It's Good For The Game
Gun work good.

## Changelog
:cl:
fix: The Twinkleshine's PML now works.
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
Did you ever stop to think maybe there was a reason it spawned without a magazine

**Comment by GuiltyNeko** [comment]
In its current state, it does not function. You cannot fire it, you cannot put a shell in. Because of the way the code works, it racks the bolt, or something, which drops the magazine, which, you can't put one in, so you can't insert a shell, because there's no magazine for it. So intended to spawn without a magazine or not, it does not WORK period.

**Comment by GuiltyNeko** [comment]
Right, looking back at the code, it sets bolt_locked to true, which I assume does something to make the magazine not exist, but the fact is, it needs a magazine or it simply won't be able to load shells, since the shells get loaded into the internal, fake magazine. Without a magazine, it is a paperweight. Without doing a significant amount of code work, it cannot be fixed properly, and with code freeze being a thing, this is the only real way to get a functional PML on the twinkleshine in a reasonable amount of time.

**Comment by dwasint** [comment]
with a code freeze this is the best we can do and we can always just remove the magazine once its actually fixed looks good map wise

**Pull request merged**
