### PR TITLE
Adds the Reticence Facility Space Ruin

### PR DESCRIPTION
**Pull request by Dethstorm**
## About The Pull Request
This PR adds the Reticence Facility Space Ruin to the server. It includes enemies, landmines, a bit of story and a small maze for you to complete. Remarkable items that it contains: Loaded Reticence Mech, Guide to Advanced Mimery Part 1, Makarov + Suppresor + 2 magazines, Sad Trombone Implant, Bananium Sword, Hunting Knife, Research Papers, and other less valuable items.

## Why It's Good For The Game
I believe that Space Ruin exploration in the server is not profitable compared to other activities (Tendril farming, planet ruins, research) as most ruins are made to be valuable for the average SS13 server and not for Shiptest. This ruin adds unique and otherwise unobtainable items that encourage players to explore space and find ruins for their loot. (I believe this ruin to be balanced as of now, due to how rare space ruins are in the map, and the amount of other ruins that could generate instead of this one)

Credits to Borbop#9109 for helping me to test the map and figuring out how to make it work. 
Credits to novaa#9928 for helping us figure out why the map wouldn't spawn.

## Changelog
:cl:Dinakeri
add: Added reticencefacility.dmm to SpaceRuins
tweak: Tweaked space.dm for the ruin to be able to spawn

/:cl:

Screenshot_1735

### CODE REVIEW

**Comment by VladinXXV** [comment]
Fun allowed

**Review by bsolomon9 — CHANGES_REQUESTED** [review]
There are 2 issues with the ruin as it stands
1. The walls in the maze aren't invisible they are just black (not an issue if that is what you want)
2. the landmines are the wrong type and only damage the things around them and not the person stepping on them

**Review by bsolomon9 — APPROVED** [review]
All issues mentioned in last review fixed, ready for TM it seems

**Comment by githubuser4141** [comment]
Mech/Projectile interactions are currently broken making mechs immune to projectiles. Are we sure pixel hunting to melee an invisible gun mech is going to be fun?

**Comment by Jackriip** [comment]
Problems I had running through this ruin:
- It is incredibly easy. those void people die in a couple of hits, there's basically no threat. Maybe buff them with var editing, or add more or up their damage or all of the above
- The mines don't hurt you at all, they explode everything around you
- The door to the vault is invincible. Completely invincible.

**Comment by JohnFulpWillard** [comment]
Please save with Tgm next time

image

**Pull request merged**
