### PR TITLE
Syndicate BDP

### PR DESCRIPTION
**Pull request by HourlyLimit**
## About The Pull Request

Well Its a drop pod with mats and all you need to get started expanding your ship and or building a base it has all your needs and extras that can help you after you set them all up

## Why It's Good For The Game

It's good for the game as we need more ships that encourage expanding in many different levels

## Changelog
:cl:
add: Added Ship BDP
/:cl:

image

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
I think you forgot to give the ship a unique name. Cyanide already exists.
Edit: And your map is in the wrong format.
Edit edit: You deleted the second CL in the PR body, so the changelog won't work either.

**Comment by GuiltyNeko** [comment]
Aaaand it looks like your map is in the wrong format.

**Comment by GuiltyNeko** [comment]
Second CL needs a slash before it.
Edit: And your engine pre-heater is backwards, and you need to have physical access because they start off, so your SMES will need to move a little.
Edit edit: And I'm pretty sure that neither pre-heaters nor engines are airtight so you'll need to put a directional window between them.

**Comment by GuiltyNeko** [comment]
It's still called the cyanide, which is still, another existing ship.

**Comment by GuiltyNeko** [comment]
"Syndicate Base Depoly Pod", I'm sure you can spot the spelling mistake.

**Comment by Jackriip** [comment]
test merging

**Comment by dwasint** [comment]
This is far better than the cyanide  the comparable ship, this needs to be either jacked up in price, or alot of the extra stuff needs to be removed

**Review by GuiltyNeko — CHANGES_REQUESTED** [review]
I need you to hook up the precharger to power. It has no terminal, nor cable going to where a terminal would be. Not everyone has the engineering brilliance to know how to hook up a SMES correctly.

**Pull request closed without merging**
