### PR TITLE
IPC Fixes

### PR DESCRIPTION
**Pull request by SELFHELL**
Totally not just removing all the jungle code and fixing IPC.

## Why It's Good For The Game
Now the jungle has something besides shitty ruins

## Changelog
:cl:
add: hopefully

### CODE REVIEW

**Comment by ShibaInuLord** [comment]
where the mooks at

**Comment by ShibaInuLord** [comment]
> Now the jungle has something besides shitty ruins

thats hurtful

**Comment by SELFHELL** [comment]
I was informed that nooks are currently broken in the codebase.

**Comment by ShibaInuLord** [comment]
> I was informed that nooks are currently broken in the codebase.

they worked for me on a local, idk then

**Comment by SELFHELL** [comment]
ok so, apparently the human traps can be ghost controled without admins. fuck

**Comment by SELFHELL** [comment]
do I call this a new ghost role or just, remove it

**Comment by SuperNovaa41** [comment]
remove it they're op

**Comment by SELFHELL** [comment]
Got it

**Comment by SELFHELL** [comment]
Now replaced with spiders

**Comment by ShibaInuLord** [comment]
which kinda spider, they're also really op

**Comment by SELFHELL** [comment]
Hunter Spider, And tested it on a local host, doesnt appear to be a whole bodymass of mobs nor general lack of em.

**Comment by Jackriip** [comment]
you should probably move some of these mobs across the multiple jungle biomes

**Comment by SELFHELL** [comment]
> you should probably move some of these mobs across the multiple jungle biomes

fhayhduyawhdwauy What else is there that is intresting

**Comment by SELFHELL** [comment]
ok there

**Comment by SuperNovaa41** [comment]
this can all be modularized really easily

**Comment by SELFHELL** [comment]
OK HOLY FUCK I SCREWED UP. SPIDER CIVIL WAR AND A FEW TO MANY MEGA ARACHNIDS

**Comment by Jackriip** [comment]
I like the idea of adding mobs to the jungle, but I don't like how this was done.

- We need to separate each mob out with a separate weight to them. 
- We should remove all the silly stuff like eyeballs, templars, goats etc. 
- Add simple mobs that aren't hostile, but match the environment.
 
Things like mega arachnids should be super rare. Gorillas should be rare. Monkeys should be less so.

**Comment by SELFHELL** [comment]
After careful consideration, this PR will be used for my jungle rework once I finish all of that

**Comment by SELFHELL** [comment]
Jungle Rework dev is currently paused due to skeleton planet

**Comment by SuperNovaa41** [comment]
Undraft when ready

**Comment by SuperNovaa41** [comment]
Hasn't seen any progress in 2 weeks, unsure of what the goal of this PR even is now

**Pull request closed without merging**
