### PR TITLE
Adds the thunderbird

### PR DESCRIPTION
**Pull request by bsolomon9**
## About The Pull Request

adds the thunderbird a BADLY needed Nanotrasen competitor to the hyena with many weapons, a mining vendor, medical, and an antimatter for the engine

image
image

## Why It's Good For The Game

there is like a single NT combat ship and the hyena is unparalleled 

## Changelog
:cl:
add: Added the thunderbird map file
add: Added the thunderbird.json in the configs 
/:cl:

### CODE REVIEW

**Comment by Greenfire575** [comment]
i am doing a brother check in, showing support for one another.

**Comment by SuperNovaa41** [comment]
Looks good, though does the hyena come with that many shift start weapons?

**Comment by bsolomon9** [comment]
well i figure that the balance is based off the hyena having cargo and this ship not despite the equal price

**Comment by Jackriip** [comment]
too many weapons
no hardsuits in the suit storage
no holopad
two cryo consoles
no button for the blast doors
eguns are broken / don't work

**Comment by NiftyRyanyan** [comment]
Remove the syndicate vendor, they really don’t need free round start syndicate weapons.

**Pull request merged**
