### PR TITLE
Modsuits-Port-(Not-Removing-Hardsuits)(still being worked on)

### PR DESCRIPTION
**Pull request by HourlyLimit**
## About The Pull Request
go here to learn more about it https://github.com/tgstation/tgstation/pull/59109
and don't worry we are not removing hardsuits!! 

- **REMMBER THIS IS NOT DONE ALSO DO NOT WORRY ABOUT THE ERRORS, I READ THEM THERE ONLY THERE BECAUSE I HAVE NOT YET PORTED IT ALL**

## Why It's Good For The Game

Well it a whole new armor set that the players can make themselves!!! what its not like we are removing hardsuits!

## Changelog
:cl:
add: Added MoD suits!!! don't worry we did not get rid of hardsuits! have fun pick and choose to make one or get the other have fun!!
/:cl:

### CODE REVIEW

**Comment by HourlyLimit** [comment]
**44 FILE LEFT LETS GO GUYS!!!**

and then you know fixes after that but thats easy

**Comment by Calyxman** [comment]
Have you tried porting bay rigs

**Comment by HourlyLimit** [comment]
> Have you tried porting bay rigs

Those feel like a mix of modsuits and hardsuits i don't really know if i would want to add it also that i might not want to do anymore big prs for a bit

**Comment by Calyxman** [comment]
Modsuits are like the worse version of rigs. Until fikou can get them to a good content level they're worse.

**Pull request closed without merging**
