### PR TITLE
Removes ship docking throwing people/objects

### PR DESCRIPTION
**Pull request by DeveloperLoser**
## About The Pull Request

Removes heavy ships throwing people and objects when they dock, ships now just knockdown players.

Done by just deleting the equation for ship throwing and instead making it = 0,  lazy but works fine. Original code is included in comment above.

## Why It's Good For The Game

Ship throwing as I call it adds nothing valuable, and lags the server. All it achieves is making people salt in chat and making larger ships incredibly messy

## Changelog
:cl:
del: Equation for ship throwing
/:cl:

### CODE REVIEW

**Comment by DeveloperLoser** [comment]
Also worth noting my ship I was testing on (twinkleshine) did run into the del() issue but I was able to dock 3 times before it happened

**Comment by SuperNovaa41** [comment]
merge master into your branch and your conflict will fix

**Comment by Dennok** [comment]
You know that you can just disable engines on landing? This remove knockbsck and throw.

**Comment by DeveloperLoser** [comment]
> You know that you can just disable engines on landing? This remove knockbsck and throw.

Sounds like a code oversight and also a kinda a pain in the ass

**Comment by SuperNovaa41** [comment]
It's definitely not a code oversight, i think was intended. But i don't really care

**Comment by SuperNovaa41** [comment]
Actually it's not a oversight at all. This was very much intended, and i think it should just be made more apparent somehow, rather than being disabled. It scales with the level of thrust your engines have. Maybe some sort of warning somewhere? to make it clear that this is being done because of powered on engines

**Comment by DeveloperLoser** [comment]
Was gonna just rework this but k I'll open a different pr tonight or something

**Pull request closed without merging**
