### PR TITLE
Update ai_laws.dm

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request
Changes the default Ai Lawset to be a modified crewsmoiv

## Why It's Good For The Game
Approved by Addust

## Changelog
:cl:
add: AI's have gotten new default lawset boards which should prevent betrayal of the crew.
/:cl:

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
You missed an or, makes the grammar strange

**Comment by SELFHELL** [comment]
How would someone be alive and unrevivable, adding an or seems pointless.

**Comment by GuiltyNeko** [comment]
"human being or," was turned into "crew member,"

**Comment by SELFHELL** [comment]
ah, I see.

**Comment by SELFHELL** [comment]
should be fixed.

**Comment by SELFHELL** [comment]
Local host requests only humans be designated as crewmembers

**Comment by SELFHELL** [comment]
Seeing as how there doesn't really seem to be any interest in this and the fact that no one really makes AI's, closing this til further notice

**Pull request closed without merging**
