### PR TITLE
Henk Ship

### PR DESCRIPTION
**Pull request by HourlyLimit**
## About The Pull Request

It's a clown ship it's like the honk ship but the layout changed and items added and **this time with its own atmo!** and an **emergency sm launch!** _for those clowns who don't care about sm's and want to blow up others with the funny yellow thing!_ 

## Why It's Good For The Game

It would be nice if we had more job-themed ships as there is only one clown ship _I also feel the honk ship may lack what I have added hrm may go edit it or get the man who made it to._

## Changelog
:cl:
add: Added Henk Ship a Ship for all your Clowney needs come on board pick a fight take down others who say clowns are weak pick on your mine friend!
/:cl:
image

### CODE REVIEW

**Comment by HourlyLimit** [comment]
**_HONK!_** _Starts to dance to discoball_

**Review by bsolomon9 — CHANGES_REQUESTED** [review]
for future prs PLEASE have a screenshot of the ship with area turned off so we can get a peak at what it is before opening sdmm. for issues the only ones i see is that on the left of the ship the buttons are on a different id from the doors, the doors share an id with the doors and buttons on the right. only other issue is that the sleeper area has no apc so if you build a machine there it wont work at all (less of a problem).

**Review by bsolomon9 — APPROVED** [review]
the day has finally come

**Comment by HourlyLimit** [comment]
Indeed

**Comment by Jackriip** [comment]
can you make this replace the other honk ship, there can only be one

**Comment by bsolomon9** [comment]
Tming now

**Comment by bsolomon9** [comment]
cant tm it due to epic tgs failure

**Comment by Jackriip** [comment]
test merging

**Comment by Sbmhawk** [comment]
You deleted the entire Honk class ship, you probably want to just disable purchasing of it

**Comment by GuiltyNeko** [comment]
Two of your left-side blast doors have the wrong ID, and your crew dorm area around the cryopod has no APC, and it doesn't need to be a separate area anyways.

**Review by GuiltyNeko — CHANGES_REQUESTED** [review]
To put it differently, you need to fix the IDs on your left-side blast doors, and either remove the sleep area and replace it with the surrounding area, or give it an APC, and optionally but preferred, remove the one tile wide area strip left of the engine room in the wall.

**Pull request closed without merging**
