### PR TITLE
!!VOIDCREW CODE FREEZE!!

### PR DESCRIPTION
**Pull request by SuperNovaa41**
Until we're done with all of the rebase work, any code directly modifying Voidcrew/Shiptest specific features is disallowed without explicit permission from a maintainer. This will help us to avoid a load of conflict errors. 

/tg/ code base fixes are OK!

Applies to all PRs made after this.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Rebase GitHub project is here -> https://github.com/orgs/voidcrew/projects/2/views/1. Here's the current PR i'm doing that involves /tg/ rebase work -> https://github.com/voidcrew/Voidcrew-LRP/pull/244.

**Comment by Addust** [comment]
mapedits allowed?

**Comment by SuperNovaa41** [comment]
> mapedits allowed?

Yes

**Comment by githubuser4141** [comment]
Is editing armor values allowed?

**Comment by SuperNovaa41** [comment]
Sure, as long as its atomic i don't really hav ean issue

**Pull request closed without merging**
