### PR TITLE
Ports the sugarcube

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
Sugarcube, as seen on shiptest. Only difference is the addition of two oxygen tanks that weren't present on the shiptest version. 

Original PR: https://github.com/shiptest-ss13/Shiptest/pull/826

## Why It's Good For The Game
More ships don't hurt, this is a bigger pill, everyone loves their pills.

image
Turret is broken, the carp suits are in a safe. Better get cracking.
## Changelog
:cl:
add: Added the sugarcube from shiptest
/:cl:

### CODE REVIEW

**Comment by Jackriip** [comment]
Pics?

**Comment by GuiltyNeko** [comment]
Ah, yeah, I can do that. For some reason I assumed everyone would be familiar.
Edit: There, donezo

**Comment by dwasint** [comment]
if not for the safe i would say bump its price but otherwise looks fine to me

**Comment by GuiltyNeko** [comment]
Well not only the safe but if you're dumb you'll get shot by the fucking glockroach.

**Comment by dwasint** [comment]
Also if you port from upstream please link the pr where the ship came from :)

**Comment by Jackriip** [comment]
test merging

**Review by dwasint — APPROVED** [review]

**Pull request merged**
