### PR TITLE
Emergency firesuit can hold big oxygen tank.

### PR DESCRIPTION
**Pull request by TheLeopold**
## About The Pull Request
Y'know, red one, that is inside the same fire closed and supposed to be used with it.

## Why It's Good For The Game
Fix I guess

## Changelog
:cl:

fix: Emergency firesuit can hold big oxygen tank.
/:cl:

### CODE REVIEW

**Comment by TheLeopold** [comment]
Don't mind the commits, I just don't know how GitHub works

**Comment by NiftyRyanyan** [comment]
Im fairly certain they are not supposed, This is more of a balance change.

**Comment by SuperNovaa41** [comment]
I dont see the purpose of that

**Comment by githubuser4141** [comment]
> I dont see the purpose of that

QoL change, makes it so you don't have to carry the oxygen tank in your hands. I think this is a good idea, the firesuit already isn't space proof and slows you down a ton

**Comment by SuperNovaa41** [comment]
Whatever idrc

**Comment by githubuser4141** [comment]
> Whatever idrc

It IS already a feature in /TG though. So I don't know if that changes things, or anything.

**Pull request merged**
