### PR TITLE
NT Class Nanopill

### PR DESCRIPTION
**Pull request by HourlyLimit**
## About The Pull Request
**Nanopill Name By Addust**

It's a pill shaped NT ship! wanting people to plant the pill and grow it if you can even do that with pills and expand the ship in the glory of NT!

## Why It's Good For The Game

More ships encouraging expanding! and one more NT ship as we all know NT has been lacking on ships!

## Changelog
:cl:
add: Added Nanopill! This is NT's way to say we need to catch up in NT ships fast! That's why NT is selling this for only 150! What a discount! (Please buy it or NT will go into bankruptcy)
/:cl:
image

### CODE REVIEW

**Comment by Addust** [comment]
thancc

**Comment by Dethstorm** [comment]
I'd say the price is way too low for the space and stuff it offers. 300 would be fair though.

**Comment by Jackriip** [comment]
Agreed, lets bump the price to like 350

**Comment by Jackriip** [comment]
test merging

**Comment by Addust** [comment]
this has the same bullshit transparent sleeper as the Cyanide and no recharger

**Comment by Addust** [comment]
there is also a lack of easily-accessible mining equipment (pickaxe, satchel, scanner)

**Comment by Addust** [comment]
nevermind on that part except for the satchel

**Comment by bsolomon9** [comment]
Played 2 rounds tm'd with the complaints fixed, Merging

**Pull request merged**
