### PR TITLE
Adds the NEU Mechaton-Class Robotics Production Facility

### PR DESCRIPTION
**Pull request by DAKKA-WAAAGH**
## About The Pull Request

image
The Mechaton is a robotics department thrown into a ship. It has everything players need in a round, while also starting them with enough resources and components to quickly build a Ripley APLU for mining (or whatever they want).

It also comes with a functioning bot patrol path and two adorable pets!
_P.S. Please clean up the oil spills to avoid any accidents_

## Why It's Good For The Game

Lets players immediately get into robotics; ship diversity is good for the game.

## Changelog
:cl:
add: Mechaton-class ship
add: Config for said ship
/:cl:

### CODE REVIEW

**Comment by Jackriip** [comment]
test merging

**Comment by theta006** [comment]
can you even make IPCs in voidcrew?

**Comment by githubuser4141** [comment]
few things I noticed,

- Mech chargers don't have a charging console
- No ore crates or wood to build them, so mining mechs can't pick up ores
- No spare high-capacity+ batteries so making a mech that doesn't run out of power in seconds is dependant on research
- No large oxygen tank dispenser
- No large oxygen canister; the "air" canister is awful and forces you to use 50+ kPa which runs out in a few minutes on small internals tanks

Nice work otherwise, I like the concept of a robotics ship.

**Comment by DAKKA-WAAAGH** [comment]
> few things I noticed,
> 
>     * Mech chargers don't have a charging console
> 
>     * No ore crates or wood to build them, so mining mechs can't pick up ores
> 
>     * No spare high-capacity+ batteries so making a mech that doesn't run out of power in seconds is dependant on research
> 
>     * No large oxygen tank dispenser
> 
>     * No large oxygen canister; the "air" canister is awful and forces you to use 50+ kPa which runs out in a few minutes on small internals tanks
> 
> 
> Nice work otherwise, I like the concept of a robotics ship.

Okay now that I go over the map again and again, I'm finding more issues, so I'm closing this PR until everything is okay. Thank you for taking the time to review it closer.

Also, I PR'd from master again because my brain is smooth so the next PR is made from a test branch.

**Pull request closed without merging**
