### PR TITLE
Touches up the listening station

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
Yesterday I noticed one of the bolted doors on the listening station had space under it. So I fixed it. Then I fixed the decals. Then I decided to touch up the rest of it a little. By which I mean I made the hall in front of the radio room slightly wider, making medical squished but overall larger. Over time I want to just generally improve this place, as I'm not really happy with it.

## Why It's Good For The Game
Space tiles under doors is bad. Space is good.

## Changelog
:cl:
add: The syndicate listneing post now has slightly more room available to begin with.
fix: The syndicate listening post no longer has space lying in wait underneath one of its doors.
/:cl:
The new look of this area.
image

### CODE REVIEW

**Comment by Addust** [comment]
there should be gear to expand the interior of the listening post, and as such the whole asteroid should be under its area

**Comment by GuiltyNeko** [comment]
> there should be gear to expand the interior of the listening post, and as such the whole asteroid should be under its area

The "gear" is a bunch of circuits inside the hidden storage room, and you're intended to mine the asteroid for materials. In addition, there's a little tiny icon in the bottom right of your screen that will make an area, or optionally, extend an area. I know it doesn't get much use here since most people use shuttles and that button doesn't work on shuttles, but it still exists, and that thing isn't a shuttle.

**Comment by Jackriip** [comment]
test merging

**Comment by dwasint** [comment]
good fixes and its been tm'd will approve and merge now

**Review by dwasint — APPROVED** [review]

**Pull request merged**
