### PR TITLE
Adds Modular Ruins Port

### PR DESCRIPTION
**Pull request by HourlyLimit**
https://github.com/tgstation/tgstation/pull/64077
## About The Pull Request

More about the pull here https://github.com/tgstation/tgstation/pull/64077

## Why It's Good For The Game

So, we can fill up our map more with unique maps even if there from the same base also Random loot + Random Map parts people always love chance, don't they?

## Changelog
:cl:
add: Added Modular Ruins
/:cl:

### CODE REVIEW

**Comment by HourlyLimit** [comment]
I will test this soon then i will make it ready for review

**Comment by HourlyLimit** [comment]
For now use this for ruins it has not yet been tested with ships so you can try if you want

**Comment by GuiltyNeko** [comment]
If you could provide an example of this working on a real map that would make it easier to merge this. As it is now, it's just a feature with nothing using it and nothing showing it operating correctly on this code.

**Comment by Addust** [comment]
Preferably with the DJ station as that's already set up on /tg/.

**Pull request closed without merging**
