### PR TITLE
Tranquility flying apartments

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
Ports the tranquility apartment complex from shiptest.
Some of the floors weren't available here, and on shiptest I guess some decals are separated into transparent and opaque, which they aren't here, so obviously I couldn't keep that part. I didn't change the cost but I'm not sure if it's a good cost either.

Original PR: https://github.com/shiptest-ss13/Shiptest/pull/1161

## Changelog
:cl: PrefabQuasar, GuiltyNeko
add: The Tranquility-class Flying Apartment Complex has been ported from shiptest.
/:cl:
image

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
Oh yeah, and I had to add to coded ship areas for this because it uses a different "dorms" area for each room which makes massively more sense than the pain that would be trying to find a different area that fits for each one.

**Comment by dwasint** [comment]
I looked into this while browsing shiptest already so i can say the mapping is fine, as for the areas i will need to wait until a codetainer looks into it

**Comment by GuiltyNeko** [comment]
It all inherits off the normal stuff since it's a subtype. It's practically more-or-less just "empty" area definitions.

**Comment by PrefabQuasar** [comment]
would appreciate being credited as the original mapper, also yes, the price on this was pretty much nonsense, as that var is no longer used for anything on shiptest main, aside from that, enjoy the map i guess? It may not be a perfect fit for your server, since i did design it purely focused around RP potential, with gameplay taking a far back seat.

**Comment by GuiltyNeko** [comment]
I can put credit in the CL, that work? And honestly, I don't think it hurts to have a ship or two that are more RP-centric.

**Comment by dwasint** [comment]
> I can put credit in the CL, that work? And honestly, I don't think it hurts to have a ship or two that are more RP-centric.

that and the link to the original pr please

**Comment by PrefabQuasar** [comment]
> > I can put credit in the CL, that work? And honestly, I don't think it hurts to have a ship or two that are more RP-centric.
> 
> that and the link to the original pr please

https://github.com/shiptest-ss13/Shiptest/pull/1161

**Comment by PrefabQuasar** [comment]
oh i thought that was directed at me i am
not smart

**Comment by PrefabQuasar** [comment]
that works, yeah, thanks

**Comment by Jackriip** [comment]
test merging

**Comment by dwasint** [comment]
can get behind this, despite the fact that we are getting alot of ships we can work that part out later as its already a big issue, looks good on my end and i've seen no reports of issues since tm will merge

**Review by dwasint — APPROVED** [review]

**Pull request merged**
