### PR TITLE
[TM] Docked ships now delete

### PR DESCRIPTION
**Pull request by SuperNovaa41**
TM until i can move ships out of docking slots when they're turned into ruins

### CODE REVIEW

**Comment by Dennok** [comment]
Why not just push it to the space and dock to space?

**Comment by githubuser4141** [comment]
> Why not just push it to the space and dock to space?

Or just have the ruined ship be 'weaker' than the newly-docked ship, i.e. so it wouldn't affect the arriving ship. I think the idea of landing a ship within an existing ship is pretty cool.

**Comment by SuperNovaa41** [comment]
> Why not just push it to the space and dock to space?

This is stupid i want people to be abke to explore planets and find them. The real solution is to just move the ship out of a landing zone

**Comment by Dennok** [comment]
I see problem in moving, since some things can last around old landing zone, loot, bodies, and what if ship bombed and has ruined floor, it lost items.

Why do ships only dock at predetermined locations?

**Comment by SuperNovaa41** [comment]
> I see problem in moving, since some things can last around old landing zone, loot, bodies, and what if ship bombed and has ruined floor, it lost items.
> 
> Why do ships only dock at predetermined locations?

This is just how shiptest designed it, it's already planned to be changed, some work just needs to be done first

**Comment by Dennok** [comment]
What about use docking comp?

**Comment by SuperNovaa41** [comment]
I'm not too familiar with the docking component myself. I do plan to look into it soon, I just haven't gotten around to it. If you want to give it a shot go for it!

**Comment by SuperNovaa41** [comment]
merging until i find a better route

**Pull request merged**
