### PR TITLE
Cricket windows grille delete

### PR DESCRIPTION
**Pull request by BBBBAface**
## About The Pull Request

deletes grille and adds a couple of windows

## Why It's Good For The Game

double grille bad

## Changelog
:cl:
removes: extra grilles under windows of cricket
adds: a couple windows to cricket
/:cl:

### CODE REVIEW

**Comment by BBBBAface** [comment]
i will fix that commit thing eventually

**Review by GuiltyNeko — CHANGES_REQUESTED** [review]
Considering this ONLY has additions and no deletions I'm 90% certain you've done it wrong somehow. Also fix the changelog.

**Comment by BBBBAface** [comment]
> Considering this ONLY has additions and no deletions I'm 90% certain you've done it wrong somehow. Also fix the changelog.

image

i guess ill re-upload

**Comment by GuiltyNeko** [comment]
What's happening is you're putting a NEW map in the shiptest/voidcrew folder while leaving the old one, and it really doesn't work that way. You need to edit the original, or at the minimum, edit the ship's config to point to the new map.

**Comment by BBBBAface** [comment]
ohhhhhh the cricket is just in the shuttles/shiptest folder not shuttles/shiptest/voidcrew, ill fix it in a second

why are they separate folders anyway?

**Review by GuiltyNeko — APPROVED** [review]
This looks good, no more double grilles.

**Comment by GuiltyNeko** [comment]
But you'll need to properly fix the changelog. The changelog as presented in-game, yes it's presented in-game, does not provide context, so your changelog will need to have that context within it. Or at least it's meant to be presented in-game, but I don't think we have things set up for that, but you should still changelog as if we do.

**Pull request closed without merging**
