### PR TITLE
The Courage Class

### PR DESCRIPTION
**Pull request by Striketester**
The syndicates response to the Bead Frigate.

- Its fast
- Its literally filled with troops
- Its cool

image

### CODE REVIEW

**Comment by Striketester** [comment]
image
hopefully final version

**Comment by Striketester** [comment]
image
up to date image of vessel

**Comment by SuperNovaa41** [comment]
Before this can be merged (in prep for https://github.com/Jackriip/Voidcrew-LRP/pull/33) could you just move the file into `_maps/shuttles/shiptest/voidcrew`, and update the config file to reflect that aswell

**Comment by Striketester** [comment]
i have zero clue how to move it

**Comment by SuperNovaa41** [comment]
dont worry about it then

**Comment by Jackriip** [comment]
I talked with @Striketester about things that need to change for this ship to get merged:
1. It needs to be less OP. Currently more powerful than the hyena. Remove the night vision and thermals and powerfist and lets see where we are at. We want combat ships to never be op enough to where you don't have to play the game (do rnd, mining, etc).
2. SMES needs to be fixed. It's the wrong type. Use /obj/machinery/power/smes/engineering
3. It needs to be bigger. There needs to be room for RND and other things like cloning etc if they set it up.
4. The cryo console is visible and usable outside the shuttle

**Comment by Striketester** [comment]
image
nerfed

**Comment by Jackriip** [comment]
@Striketester Can you add "prefix: SYN-C" to the json for this?

**Pull request merged**
