### PR TITLE
Adds colored stripes to departmental protolathes/techfabs Port

### PR DESCRIPTION
**Pull request by HourlyLimit**
## About The Pull Request

Read more on it here [(https://github.com/tgstation/tgstation/pull/64889)]

## Why It's Good For The Game

Adds extra flair to the autolathes and lets me do something else i want later with the stripes

## Changelog
:cl:
add: Added colored stripes to departmental protolathes/techfabs
/:cl:

image

### CODE REVIEW

**Comment by HourlyLimit** [comment]
WOOO MY FIRST PORT DOWN AND MESSING WITH THE CODE TO MAKE IT WORK!!!!!

**Comment by Jackriip** [comment]
I don't think we use departmental lathes

**Comment by HourlyLimit** [comment]
> I don't think we use departmental lathes

I been planning on making something with this if it gets merged and also its nice for mappers when we want to make a ship with departmental lathes

**Comment by Jackriip** [comment]
Make your things first, this wouldn't really change anything in game atm so I'm going to close it

**Pull request closed without merging**
