### PR TITLE
Cuts ship costs and makes more ships roundstart available

### PR DESCRIPTION
**Pull request by ModDownloading**
## About The Pull Request

Reduces the cost of many ships that are either poorly equipped (the tide ships and most whiteships) or are only really effective at one thing (the boyardee and pubby light carrier, and similar ones). Also make more ships available roundstart and makes some of the ships that aren't particularly strong have a chance to show up at roundstart, using the strength of the Riggs ship (which already spawns roundstart) as reference. All new roundstart ships are that strength or weaker.

## Why It's Good For The Game

Pill ships are cool and all, but this should give much more variety of ship types that players can regularly use without making them play for several hours just for access to a decent ship. This also won't lead to people constantly choosing the best equipped battleships since most of the ships with reduced cost are the kind without many combat abilities or good equipment readily available.

The ship prices are not final, if you think any of them should be reduced more or not reduced as much, please let me know!

## Changelog
:cl:
add: More ships are available roundstart overall, and more ships are added to the pool of possible roundstart ships
tweak: Reduced the cost of most of the lesser equipped ships
/:cl:

### CODE REVIEW

**Comment by dwasint** [comment]
re-adding combat ships to roundstart is a no go. Also ships like the meta were already really solid for its price point. I agree that ships need a re-evaluation cost wise but the costs on alot of these are mostly way to cheap

**Comment by ModDownloading** [comment]
@dwasint Ok, removed Libertatia from roundstart and removed the forced one pair of combat ships. Some of the cheaper costs were just to give people with less than 200 coins an option that they can choose fairly regularly that isn't a pill ship. If they're too low, which costs do you think should be higher? I'll definitely consider changing prices and I'm actually looking for feedback.

**Comment by ShibaInuLord** [comment]
> @dwasint Ok, removed Libertatia from roundstart and removed the forced one pair of combat ships. Some of the cheaper costs were just to give people with less than 200 coins an option that they can choose fairly regularly that isn't a pill ship. If they're too low, which costs do you think should be higher? I'll definitely consider changing prices and I'm actually looking for feedback.

the reason that they're so expensive is to make people join the same crews, instead of 20 solo ships, aka you're not meant to be able to choose regularly, although some things like the lamia being 777 is too expensive

EDIT: lmao out of all the ships you could've reduced the price on you didnt do the lamia

**Comment by ModDownloading** [comment]
@ShibaInuLord I didn't reduce any ship with a price that wasn't a multiple of 10 (like the 426 for the Wright ship or 667 for the Anomaly ship) because I figured those might be references to something, also the Lamia looked like it was a fancy ship like the High-class that might deserve a higher cost due to "BLING" even if it's poorly equipped otherwise.

As for the solo ships issue, the people who want to have ships to themselves are already just buying pill ships (according to Discord it's the most popular ship to get by far), so I thought that reducing the price of other ships might just increase variety of ships among people who already don't want to join other people's crews. Hopefully these slightly larger ships will encourage new people to join the crew of a ship that probably would've been just another pill otherwise.

If I should reduce the cost of the Lamia ship, what do you think is a reasonable number to put it at? I'd be happy to make a change if it really is overpriced for what it is.

**Comment by ilikesaying** [comment]
the advent of password costs for ships kind of made friend-only crew ships more expensive, not to mention having to deal with or killing randoms if the buyer didn't know they had to buy a password lock or they couldn't afford it.

**Comment by SuperNovaa41** [comment]
Dumb

**Pull request closed without merging**
