### PR TITLE
Massively upgrades the forgotten ship.

### PR DESCRIPTION
**Pull request by Addust**
## About The Pull Request

Gives it an RnD server board so its lathes work, gives it the functional kind of shuttle engine, gives it some more windows and a numerical sign helping to indicate its designation (SCSBC-12), some aesthetic updates, gives it the equipment needed to upgrade into a fully functional flyable shuttle hopefully, fixes rotation on some of the crew sleepers, and adds a little more cabling leading through the Captain's quarters allowing ion engines to get power. Also gives the cap's quarters a maint door. Also adds a shitton of syndie logos. They can also use the RSD to build a deployment pod, letting them pack up and fly off. I've also given them a Cybersun autosurgeon, a bunch of implants including a bugged-out laser implant, and a few extra misc things such as emergency spacesuits.
image
image

## Why It's Good For The Game

Makes this ghostrole more useful and allows them to eventually take flight on their shuttle, while also giving them a nice view outside of the bridge.

## Changelog
:cl:
add: Massively upgrades the forgotten ship!
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
when review

**Comment by Addust** [comment]
BUG NOTE: The RSD (Rapid Shuttle Designator) doesn't function since the ship counts as an indoors area, too lazy to fix

**Comment by Dennok** [comment]
Now the problem is that RSD (Rapid Shuttle Designator) completely doesn't work. It cant properly create ship.

**Comment by Addust** [comment]
okay but I'll leave it there so if it gets fixed players can fuck around

**Comment by dwasint** [comment]
I'm split on this as it won't work as a normal ship, but at the same time it looks good

**Comment by Addust** [comment]
DO NOT MERGE RIGHT NOW, SOME ADDITIONAL CHANGES ARE IN PROGRESS

**Comment by Addust** [comment]
New changes include: Dedicated ship armory with an upgraded turret, telecomms so that radio works, removes the elite guy and replaces them with 2 regular guys (one in bridge one in meeting room, can revert if requested but jesus fucking christ they're unbalanced), weakens one of the NT scum in crew quarters, makes the med vendor free, and some other shit. Also a blast door for the cargo pod

**Comment by Addust** [comment]
also more non-cybersun hardsuits (3 regular Gorlex hardsuits in the south airlock and the captain now gets an elite hardsuit)

**Comment by Addust** [comment]
and funny magcleavers

**Comment by Addust** [comment]
image
image
Okay upgrade's finished, clear for final review and merge

**Comment by Addust** [comment]
Also, the telecomms server starts off but can be activated by the crew once they've recaptured the bridge.

**Comment by Addust** [comment]
Performing difficulty testing. Due to the situation ghostroles are normally placed in they should be able to secure the ship solo with what they get.

**Comment by Addust** [comment]
Ye, ghostroles can indeed survive this so long as they know what they're doing.

**Comment by Addust** [comment]
performing some minor QA testing to ensure some things are possible like large amounts of sci with the limited resources the ship gets

**Comment by Addust** [comment]
yup, but some designs may be hard to get

**Comment by Addust** [comment]
made some qol changes to make shit look better

**Comment by Addust** [comment]
oh also syndie signs

**Comment by Addust** [comment]
why is this taking so long to get merged

**Comment by dwasint** [comment]
I'm still split on this as i don't think this ship can ever take off as its not classified as a shuttle. I'm iffy on ghost roles in general until we can make shuttles from scratch period as they would run out of resources and be kinda stuck

**Comment by Addust** [comment]
I can make it a capable shuttle and also make its surrounding turfs passthrough meaning you can spawn it on any planet as an admin.

**Comment by Addust** [comment]
just made a version designed to be a capable shuttle

**Comment by Addust** [comment]
nevermind i don't wanna break the shuttle system, shuttle version will not be added

**Comment by Addust** [comment]
they now have a cybersun autosurgeon that has increased surgery speed alongside a buncha implants to use with said autosurgeon. cybersun moment

**Comment by Addust** [comment]
what

**Pull request closed without merging**
