### PR TITLE
Adds Wrecker-class Mobile Crash Site ship (v1)

### PR DESCRIPTION
**Pull request by ChronicPwnage**
## About The Pull Request
Adds the Wrecker-class Mobile Crash Site ship. Your friendly neighborhood dwarf was just drinking his way on over to the local pub when he accidentally lost control and well...
image

Luckily his little stout ship was far too robust for a little destruction and vehicular homicide to slow it down for long! With a little cleaning up, the accident might even be considered an upgrade.

image

The Mobile Crash Site is a medium sized, simple ship with a focus on mining and making use of the Mining Equipment Vendor to upgrade equipment, fix up the ship, and eventually expand it. It has one hardsuit, two survivor suits, and some basic mining equipment. The Ore Silo and Mining Equipment Vendor can help kickstart mining efforts in the long run. While messy, the added space of the recently-detached asteroid bar can be refitted into medical or research facilities, and much more.

## Why It's Good For The Game
With plenty of large complex ships already in the game, as well as plenty of the ubiquitous pill ships, a medium-sized ship with decent space and flexibility fits a nice role for people who want the freedom of design given by pill-style ships with more space, structure, and a fun base theme.

## Changelog
:cl:
add: Added the Wrecker-class Mobile Crash Site ship.
/:cl:

### CODE REVIEW

**Comment by ChronicPwnage** [comment]
Updated screenshots with current version.

**Comment by dwasint** [comment]
Don't have tgs access so i can't tm it right now but it does look good from my local testing will approve and see if someone can tm it for a bit

**Review by dwasint — APPROVED** [review]

**Comment by GuiltyNeko** [comment]
Test merging

**Review by GuiltyNeko — CHANGES_REQUESTED** [review]
You need a prefix in the json or else the game will drop it to the bottom of the list for some reason, below even the combat ships.
In addition, your cryo console in in the wall, meaning it can't be accessed without popping into the cryopod and back out. You need to place it on a nearby open tile, such as the tile the cryopod is on, and nudge it onto the wall. 
And don't use bar tables. Bar tables are night indestructible and push anyone who isn't a bartender off of them if they climb them.
There's also a single tile of floor/wood/cold that I think you didn't intend to be there.
You also have a single tile of deadspace on all edges of the map. Always tighten the map boundary as far in as you can, as a general rule of thumb.

**Comment by ChronicPwnage** [comment]
Thanks for the review, I've made the following changes:

Fixes:
- Removed misplaced /floor/wood/cold tile
- Replaced bar tables with regular wooden tables
- Removed 1 tile of empty space from around the ship
- Moved cryo console so that it is accessible from a non-cryopod tile
- Added missing power cable under the generator

Modification: 
- Replaced safe with different version which accepts items spawned on top of it
- Added 3000 credits, 1x Double Barrel Shotgun, 4x Laser Slugs, and 1x Bandolier to the safe
- Adjusted stools slightly
- Replaced 2x Manual Mining Scanners with 2x Automatic Mining Scanners (lesser)

**Comment by ChronicPwnage** [comment]
Note: requires #444 in order for the signs to appear correctly (otherwise half of them will be invisible)

**Review by GuiltyNeko — CHANGES_REQUESTED** [review]
The left rear engine has a space tile under the plasma glass in front of it that I only just noticed, and you still have a bar table in the corner. Other than that it's fine from what I can see.
New item, your nanomed in the bathroom should be placed on the adjacent wall and shifted onto the wall, otherwise it can be accessed from both sides of the wall which isn't ideal.

**Comment by ChronicPwnage** [comment]
Fixes:
- Added missing tile above left engine
- Replaced bar table with regular wooden table
- Moved nanomed

**Review by GuiltyNeko — APPROVED** [review]
I'll testmerge this again next time I do another testmerge.

**Pull request closed without merging**
