### PR TITLE
Adds a Debug ship for easier testing

### PR DESCRIPTION
**Pull request by DeveloperLoser**
## About The Pull Request

Adds the Admeme class Debug ship

## Why It's Good For The Game

Testing shit is kind of a pain in the ass, so this makes it a little easier. It has void engines, magical smes, armory with a whole lot of guns and stuff in it, rnd, full chem setup, abductor toolbelt, arcd, upgrades, a silo with resources, every job clothes vendor, and ill be adding other stuff that's suggested, since that's easier than trying to think of every single possible thing

debugship

Currently im getting a runtime when trying to spawn the ship, it seems to not be given a name(the docking port, at least).
## Changelog
:cl:
add:  Admeme class Debug ship
/:cl:

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
Need to convert your map to TGM format. Go to SDMM's settings, file>preferences, for map save format select TGM, then re-save it.

**Review by GuiltyNeko — CHANGES_REQUESTED** [review]
This is perfect, exactly what I wanted. Obviously, change the price.

Also, unfortunately and tragically, it seems to be tremendously broken. It sits in the ship spawn area and doesn't get moved out of it. Until this is fixed, this absolutely cannot get merged at all. I tried looking at it the best I can come up with is that the docking port might need edits to its vars.

**Comment by Addust** [comment]
use plastitanium windows

**Comment by Addust** [comment]
also, it's gotta be shuttlemanipulator spawn only (or so expensive it causes runtimes)

**Comment by DeveloperLoser** [comment]
> also, it's gotta be shuttlemanipulator spawn only (or so expensive it causes runtimes)

Yea it wont have a price so itll be shuttle manipulator

**Comment by DeveloperLoser** [comment]
> This is perfect, exactly what I wanted. Obviously, change the price.
> 
> Also, unfortunately and tragically, it seems to be tremendously broken. It sits in the ship spawn area and doesn't get moved out of it. Until this is fixed, this absolutely cannot get merged at all. I tried looking at it the best I can come up with is that the docking port might need edits to its vars.

yea I've asked for help with this multiple times now but no one knows

**Comment by Addust** [comment]
SMES terminals are input

**Pull request closed without merging**
