### PR TITLE
Hud Restyle and Bag Restyle Port (Bodys or faces are not added with this)

### PR DESCRIPTION
**Pull request by HourlyLimit**
## About The Pull Request

More about the port here
https://github.com/shiptest-ss13/Shiptest/pull/1469
https://github.com/shiptest-ss13/Shiptest/pull/1480

## Why It's Good For The Game

Makes our sprites look nicer

## Changelog
:cl:
add: Added Hud and Bag Restyles
/:cl:
image
image
image
image

### CODE REVIEW

**Comment by Jackriip** [comment]
are they nicer tho, those human faces look awful

**Comment by Jackriip** [comment]
ill keep it if you remove the human face changes

**Comment by HourlyLimit** [comment]
> ill keep it if you remove the human face changes

they don't change the faces thats just ship test's body that the stuff is on and the body is not ported

**Comment by GuiltyNeko** [comment]
I personally prefer the old medhud UI, but the bags are great.

**Pull request closed without merging**
