### PR TITLE
Bead Class

### PR DESCRIPTION
**Pull request by Striketester**
This is the combat based variant of the Bubble class, mostly made due to a lack of NT combat vessels.

### CODE REVIEW

**Comment by Jackriip** [comment]
Would you mind dropping a pic in here?

**Comment by Striketester** [comment]
image

**Comment by NiftyRyanyan** [comment]
This looks unnecessary very little is different from bubble. Maybe look into replacing one of the rooms for a security room / changing the color scheme.

**Comment by Striketester** [comment]
the majority of changes are in crew comp instead of assistants its corporate sec

**Comment by Jackriip** [comment]
> This looks unnecessary very little is different from bubble. Maybe look into replacing one of the rooms for a security room / changing the color scheme.

Yep I agree with this. Hadn't seen the bubble previously but after checking it out this is almost an exact copy, which we definitely don't want.

**Comment by Striketester** [comment]
image

**Comment by Striketester** [comment]
new version

**Comment by Striketester** [comment]
image

**Comment by Striketester** [comment]
hopefully the final version

**Comment by Jackriip** [comment]
Seems like sec guards on bead spawn with a pistol mag but no pistol. There also needs to be a few rechargers

**Comment by Striketester** [comment]
all sec spawn with the mag btw

**Comment by Striketester** [comment]
image

**Comment by Striketester** [comment]
and here is the fixed version

**Pull request merged**
