### PR TITLE
Shuttle delete crushed things on landing more hardly.

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

No more mob loot, gibs and fueltanks appear on your ship when you land on planet.

## Why It's Good For The Game

Less trash, and buggs,

## Changelog
:cl:
tweak: Shuttle landing deete all cruched thing.
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
Not sure about this, i like seeing mobs get gibbed by planets.

**Comment by Dennok** [comment]
What if i make mobs steeel gib but items be destoyed? Since i see fueltanks appearing on your ship when you and on rock is bad.

**Comment by SuperNovaa41** [comment]
Sure

**Comment by SuperNovaa41** [comment]
undraft when done

**Comment by VladinXXV** [comment]
> Not sure about this, i like seeing mobs get gibbed by planets.

This is actually really annoying and I think it's better to do away with it. You can't really stop yourself from landing on mobs, and if you are unlucky you'll land on one in a way that fills your air supply with gibs, which are a pain to clean when they're in there.

**Comment by SuperNovaa41** [comment]
we can test it out

**Pull request merged**
