### PR TITLE
Fixes ai eye from being deleted

### LINKED ISSUE #83: [BUG] AI loses Eye when ship docked
## Round ID:

178
## Reproduction:
1. Be AI on the ship
2. dock to a planet
3. get spammed by million of "ERROR: Eyeobj not found. Creating new eye..." messages
4. Profit
5. ???
6. Somehow get everyhing fixed after 5 mins or so

### PR DESCRIPTION
**Pull request by HourlyLimit**
## About The Pull Request
This ports a fix from shiptest for the ai eye.
more here https://github.com/shiptest-ss13/Shiptest/pull/690

## Why It's Good For The Game
So people can play ai without fear of going blind forever

## Changelog
:cl:
fix: AI eye will no longer be deleted by docking/undocking
/:cl:

### CODE REVIEW

**Comment by HourlyLimit** [comment]
works ais are now safe from blindness

**Comment by Dethstorm** [comment]
We seriously needed this. Speedmerge

**Comment by ZephyrTFA** [comment]
Credit the original authors, this is required by AGPL.
Or just copy the git history, but that's a lot of work

**Comment by HourlyLimit** [comment]
> Credit the original authors, this is required by AGPL. Or just copy the git history, but that's a lot of work

Sorry about that it slipped my mind at the time to look for the person who made the code i will now add the link

**Comment by GuiltyNeko** [comment]
The shiptest PR this is ported from mentioned an issue with being shoved back to the core from a shell for no apparent reason, but in my testing this only happened the first time the ship I was in docked, and didn't occur afterwards.

**Review by GuiltyNeko — APPROVED** [review]
Works as advertised, doesn't create new problems.

**Pull request merged**
