### PR TITLE
Adds Infiltrator Wreckage as a new SpaceRuin

### PR DESCRIPTION
**Pull request by Dethstorm**
## About The Pull Request
Adds a new SpaceRuin to the current pool, with early to midgame loot like a full syndicate toolbox, a supressed sketchin, and two Syndicate Cyborg Boards, Saboteur and Medical. This ruin features a challenging miniboss that may or may not make your life hell.
Screenshot_2032
(Screenshot outdated, missing the miniboss, otherwise the same)

## Why It's Good For The Game
Because more ruins are needed, and the old ones are horrible.

## Changelog
:cl:
add: added infitratorwreckage.dmm to SpaceRuins
tweak: tweaked space.dm to allow for the ruin to spawn
/:cl:

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
I like having more obtainable syndie borg modules, but the problem is, I honestly feel like these aren't that difficult to get, considering that the syndie mediborg has restorative nanites, among all the other ridiculous things it can do, which makes this honestly very little effort for powerful stuff. If you can shove them in a locked locker with an unobtainable access (we ought to have one of these in the code anyways, I imagine) it'd be a bit better. Syndicate cyborg modules might honestly be the most powerful combat items we have so having them so easy to obtain is probably not the greatest.

**Comment by Addust** [comment]
the maintainer has spoken. i'd say having a few damaged infiltrator turrets (the penetrator kind) fire at approaching people. although this may result in a combat ship picking up the infiltrator and taking the turrets (which can occur, as once i spawned the forgotten ship, an energia hit it, and it was attached to said energia)

**Comment by Dethstorm** [comment]
Ruin is undergoing some balancing, attempting to add a syndicate cyborg simplemob to defend the ship. Penetrator turrets are NOT being added, those are extremely devastating and can also be nullified by being a syndie, therefore having a biased ruin. I'll push a commit with the changes soon.

**Comment by Dethstorm** [comment]
Fixed cyborg boards, the areas, and added a miniboss to balance the ruin. Removed a single space shark, and changed a window for a wall.

**Review by GuiltyNeko — CHANGES_REQUESTED** [review]
It all looks good, but you've got quite a few tiles that have air on them when it spawns that are exposed to space. The closed rooms are fine, but the rooms that are in space should be completely airless, no need to spend processing on atmosphere in rooms that start out exposed to space.

**Comment by Dethstorm** [comment]
fixed the air

**Review by Dethstorm — COMMENTED** [review]
yes i fixed the air

**Review by GuiltyNeko — APPROVED** [review]

**Comment by GuiltyNeko** [comment]
Looks good but I'd like a maptainer to peek at it anyhow.

**Review by bsolomon9 — APPROVED** [review]
image
It seems fine from a mapping view

**Comment by GuiltyNeko** [comment]
Test merging

**Comment by BBBBAface** [comment]
The borg defending the boards is incredibly tanky, even using frag nades and a ridiculous level of blaster fire it still killed my entire crew with half health remaining. It should probably be toned down a couple notches.

**Comment by Dethstorm** [comment]
Drafted due to lack of time to solve issues with it

**Pull request closed without merging**
