### PR TITLE
Adds the Blackbeard Heavy Boarder (re-FIXED)

### PR DESCRIPTION
**Pull request by magicaltheonething**
## About The Pull Request
Adds the Blackbeard, a "cheaper" alternative to combat NT flagships more reliably
blackbeardarea2
blackbeardnoarea2

## Why It's Good For The Game
well with the introduction of the phalanx and other combat vessels, I'd figure id add one more, this ship offers more fire-power than a normal courage, two extra crew-mates, one being a medic and the other just a normal syndicate trooper. It'll be good for the game because hopefully it'll break up the current dynamic of buying a courage and mopping the floor, not that there's anything wrong with that, just that the courage gets boring and needs more room to be cooler. AND if ship to ship boarding and interdiction pulses and all that stuff ever get added, this ship was made for it already, so there will be no need for a re-design of it.

## Changelog
🆑
add: Blackbeard.dmm in the voidcrew folder for shuttles
add: blackbeard.json added in map config
/🆑

### CODE REVIEW

**Comment by dwasint** [comment]
Okay did some testing, everything looks good in terms of the space travel. Few small things. One fix the line endings ie upload using github desktop. Second, the generators currently don't spawn with the ship making it run out of power slowly. Third, aside from the inital vendor ticket syndicates don't start with any money, so they can't really use the vendors

**Comment by theta006** [comment]
> Okay did some testing, everything looks good in terms of the space travel. Few small things. One fix the line endings ie upload using github desktop. Second, the generators currently don't spawn with the ship making it run out of power slowly. Third, aside from the inital vendor ticket syndicates don't start with any money, so they can't really use the vendors

this is a issue for all syndi ships but when you are killing and looting people money shouldnt be that big of a deal

**Comment by Jackriip** [comment]
Yeah unfortunately syndicates don't get paid ATM. They do get bank account IDs in their notes, but they aren't included by default on their ids. But yeah the timed payments don't work for them

But that isn't the problem of this ship and they should stay

**Comment by Jackriip** [comment]
But that isn't the problem of this ship and they should stay

**Comment by Jackriip** [comment]
Also @theta006 please remove the SAW, that's insanely powerful

**Comment by magicaltheonething** [comment]
> Okay did some testing, everything looks good in terms of the space travel. Few small things. One fix the line endings ie upload using github desktop. Second, the generators currently don't spawn with the ship making it run out of power slowly. Third, aside from the inital vendor ticket syndicates don't start with any money, so they can't really use the vendors

So I looked at the ship, ill fix the line editing this in github desktop or whatever, i ran the ship, generators spawned with it, and as theta said what syndicate vessel actually does research and stuff

**Comment by Jackriip** [comment]
@magicaltheonething Remove the SAW, too OP

**Comment by magicaltheonething** [comment]
alright, I removed the L6, replaced it with three new guns, and NT Boarder, an NT SABR, and a Cycling shotgun, all Syndicate-ized of course. I also fixed atmos issues

**Comment by magicaltheonething** [comment]
> @magicaltheonething Remove the SAW, too OP

i did, gotta update the pic

**Comment by dwasint** [comment]
your using an out of date branch of voidcrew super generators build path should be /obj/item/circuitboard/machine/pacman/uranium but you have them as /obj/item/circuitboard/machine/pacman/super

**Comment by magicaltheonething** [comment]
> your using an out of date branch of voidcrew super generators build path should be /obj/item/circuitboard/machine/pacman/uranium but you have them as /obj/item/circuitboard/machine/pacman/super

ah goddamnit alright ill fix that too

**Comment by magicaltheonething** [comment]
after two hours of forgetting what i was doing, the blackbeard got its generators updated

**Comment by theta006** [comment]
> after two hours of forgetting what i was doing, the blackbeard got its generators updated

is sanity the cost of mapping?

**Pull request merged**
