### PR TITLE
Adds the NT-C Hemlock

### PR DESCRIPTION
**Pull request by magicaltheonething**
## About The Pull Request
hemlockarea
hemlocknoarea
Adds the Hemlock-Class Combat Frigate

## Why It's Good For The Game
NT has like three ships, all more Expensive + this counters the Cyanide

## Changelog
:cl:
add: Added new things
/:cl:

### CODE REVIEW

**Comment by magicaltheonething** [comment]
there was never a previous Hemlock PR

**Comment by GuiltyNeko** [comment]
You still have a precharger hiding behind your autolathe.

**Comment by magicaltheonething** [comment]
they can unwrench it

**Comment by dwasint** [comment]
i'd move the autolathe up 1 tile to not cause un-needed annoyance otherwise looks good

**Comment by magicaltheonething** [comment]
i moved the lathe up and removed the cycle helpers

**Comment by GuiltyNeko** [comment]
> they can unwrench it

You... can't unwrench autolathes.

**Comment by Jackriip** [comment]
I think I like this more https://github.com/voidcrew/Voidcrew-LRP/pull/419

**Pull request closed without merging**
