### PR TITLE
adds the NEU Conquest

### PR DESCRIPTION
**Pull request by magicaltheonething**
## About The Pull Request
Conquestnoarea1
Conquestarea1
Adds the Conquest for the Starsector Sweep

## Why It's Good For The Game
Another relatively cheap capital, and because its like the Third Capital in the game cool events and shit could happen with it. And also its a Starsector ship

## Changelog
:cl:
add: Added new things
/:cl:

### CODE REVIEW

**Comment by magicaltheonething** [comment]
still no clue what these checks do or how they work, ship is fine

**Comment by GuiltyNeko** [comment]
You spelled "SolGov" as "Solgov" and it doesn't appreciate the lowercase G.

**Comment by magicaltheonething** [comment]
it passed the bot is stupid and doesnt know shit

**Comment by magicaltheonething** [comment]
I added two new types of walls, titanium and plastitanium so the ship looks nice when merged with the original colors it was designed for.

**Pull request closed without merging**
