### PR TITLE
Nukes Space Pods

### LINKED ISSUE #116: space pods cant move and shoot plasma cutters
Issue reported from  Round ID: 204 (Voidcrew-LRP)

Reporting client version: 514.1575

move where you are shooting with plasma cutters you will hityourself

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About The Pull Request

Closes #116 by association.

Nukes Space Pods from the codebase since they're shitty, in the way of the rebase, and @SuperNovaa41 said I could smash things. This PR *should* catch everything but I might have missed some small stuff.

A couple ships heavily integrate spacepods into their design and will need fixing to work. I've removed ships that only have a couple spacepod references in their .dm.

## Changelog
:cl: Swept
del: Removes Space Pods
/:cl:

### CODE REVIEW

**Review by SuperNovaa41 — APPROVED** [review]
Looks fine, just need the maptainers to take a look

**Comment by SweptWasTaken** [comment]
> Looks fine, just need the maptainers to take a look

Tested all ships modified in this PR on my debug client and they are fully functional. The only ship I have removed from the purchase list is the pubby since that ship is built around space pods.

**Comment by dwasint** [comment]
Maps look fine to me, didn't see any issues with it.

**Comment by SuperNovaa41** [comment]
mmmmmerging

**Pull request merged**
