### PR TITLE
Fix for some shuttle landing breaks.

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

Somettimes shuttle fail to gib some mobs, and this stop half of ship from landing . This PR must fix this.

## Why It's Good For The Game

Less shuttle breaking.

## Changelog
:cl:
fix: Fix shuttlle langing gib. Shutttle gib now more robust.
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
I'm like 99% certain the thing breaking the ships would be landing on other ships. However, we could definitely try this out, I see nothing wrong with that.

**Comment by Jackriip** [comment]
test merging

**Comment by Dennok** [comment]
I try to catch error with landing ship on ship, but get only "too long baseturf list" error. 
And found error when shuttle lands on mob, that i fix here.

**Comment by Mantlecrawler** [comment]
Was able to land in other ships before this was merged, so I don’t think there’s a bug there

**Comment by SuperNovaa41** [comment]
> Was able to land in other ships before this was merged, so I don’t think there’s a bug there

Thats not what this is fixing

**Pull request merged**
