### PR TITLE
Donut-Class Whiteship, rebuilt for the void

### PR DESCRIPTION
**Pull request by Addust**
Foreword: This ship starts destroyed in /tg/, so I've taken a lot of liberties with the design of the rebuilt model of the Donut.

## About The Pull Request

Adds the Donut whiteship to the game, costs 500 voidcoin same as the other whiteships.
Departments:
Command
image
Cargonia
image
Medical Bay
image
Engineering
image
Crew Quarters
image
Central Hallway
image
Aft Hallway
image
Whole Ship
image

What does the ship get, you may be thinking?
Well,
-a scrap crate with some plasma, metal, shards, and maint lot
-20 sheets of plasma in engineering
-materials in engineering
-an Alcohol-O-Mat, an older booze-o-mat that takes less of a beating
-spare set of captain gear
-full atmos system with 2 scrubber outlets, both mounted on the ship's exterior
-8 engines, same as the Donut ship certainly would have before going el kablooey
-an old equipment bin in medical with 3 ancient first aid kits
-an overstocked ration crate
-d o n k
-GPS units
-mining gear

## Why It's Good For The Game

More ship good.

## Changelog
:cl:
add: The Donut whiteship is here. 500 voidcoins and it's yours my friend!
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
image

**Comment by dwasint** [comment]
aside from it failing linters it looks okay, i do worry about it use though. This may be out of scope for this pr and maybe should be its own pr but it should be added to the possible list of spawning ships

**Comment by GuiltyNeko** [comment]
It's failing because it doesn't like the name of the docking port's "ID" variable. Says it's invalid. The var name itself.

**Comment by Addust** [comment]
what's wrong with the ID

**Comment by GuiltyNeko** [comment]
Voidcrew docking ports do not have ID variables, is the problem. That var does not exist on docking ports on our code, you'll need to remove it.

**Comment by GuiltyNeko** [comment]
Test merging

**Pull request closed without merging**
