### PR TITLE
Condor Carrier

### PR DESCRIPTION
**Pull request by magicaltheonething**
## About The Pull Request
CondorArea
CondorNoArea
Adds the Condor Carrier, and also (hopefully) Creates a new job for players with the changes to the security_officer.dm

## Why It's Good For The Game
It would be cool to at least have an attempt at a Carrier to the game, would make space battles more interesting other than just running after people in 0G

## Changelog
:cl:
add: Condor.dmm, NEU_condor.json, and Added Pod Pilot Job for the ship
/:cl:

### CODE REVIEW

**Comment by magicaltheonething** [comment]
I dont know what these checks are for or how to fix them

**Comment by GuiltyNeko** [comment]
It's not your fault the checks are failing, probably.

**Comment by magicaltheonething** [comment]
what can be done to fix the checks

**Comment by GuiltyNeko** [comment]
You need someone to re-run the checks. Looks like another PR failed the same way, so it's not a you thing.

**Comment by GuiltyNeko** [comment]
Besides, didn't we get rid of space pods?

**Comment by magicaltheonething** [comment]
i dont know i never heard about the removal

**Comment by GuiltyNeko** [comment]
Have you tested to make sure this ship works on the latest version?

**Comment by magicaltheonething** [comment]
oh right i have to unfuck the condor old assests are breaking it not allowing it to pass checks

**Pull request closed without merging**
