### PR TITLE
Fixes autolathe and catwalk dupe bugs

### PR DESCRIPTION
**Pull request by Boxlta**
## About The Pull Request
Fixes two duplication bugs. One with catwalks and the other with the autolathe
## Why It's Good For The Game
dupe bugs bad or something idk
## Changelog
:cl:
fix: fixed two dupe bugs
/:cl:

### CODE REVIEW

**Comment by Dennok** [comment]
I thik this is wrong way to fix autolathe dupe, since we already has material system and material items, like toolbox, has set used materials amount right.
Your way make things cost 1,6 times more for un upgraded autolathes, and it no more give full material return for recycled items.

**Comment by Boxlta** [comment]
> I thik this is wrong way to fix autolathe dupe, since we already has material system and material items, like toolbox, has set used materials amount right. Your way make things cost 1,6 times more for un upgraded autolathes, and it no more give full material return for recycled items.

The autolathe fix is how teegee fixed it. The other way i can see would be to make parts not do anything, or to make them increase the speed

**Comment by Dennok** [comment]
Why not #192 way? Items aready has list of materials that used in it. When you put item in autolathe item mats added to autolathe storage.

**Comment by SuperNovaa41** [comment]
Yeah, i would like to go with both ways, if you remove the autolathe fix ill merge this

**Comment by Boxlta** [comment]
> Yeah, i would like to go with both ways, if you remove the autolathe fix ill merge this

ight

**Comment by Boxlta** [comment]
closing and seperating

**Pull request closed without merging**
