### PR TITLE
Space Ruin - Nanotrasen office

### PR DESCRIPTION
**Pull request by BBBBAface**
A ruin that I made for Shiptest that I have made compatible with this codebase

Adds a new ruin, a semi-recently abandoned Nanotrasen office building. This is my first ruin, and now that I have familiarized myself with the tools and processes involved, I will be making larger ones in the near future.

There is a decent amount of gear in this ruin, with the main loot item being an Origami handbook and a couple handguns, as well as two security lockers full of the default loot. However, this is all defended by a couple dozen stickmen and stickdogs, as well as Mjor the Creative.

Extended list of loot:
The Art of Origami
Dronespeak Manual
Random Manual x4
Commander x2
SecTech vendor
Security Officer's Locker x2
Jukebox
Personal Ai device
Paperwork the sloth
Deep Fryer x2
Microwave x2
Refrigerator (with milk and eggs) x4
Super P.A.C.M.A.N. 
Uranium sheet x5
Worn-Out Insulated Gloves
Hundreds of sheets of paper
Genius research papers (hidden)

I affirm that I have tested all of my proposed changes and that any issues found during testing have been addressed.

## Why is it good for the game?

We need more ruins, especially in space, and is an interesting one to explore. There is decent loot and a high risk of death due to many enemies. I've run through it with the starter gear from a couple of ships, and while it is difficult, it isn't impossible.

### CODE REVIEW

**Review by GuiltyNeko — CHANGES_REQUESTED** [review]
You've got extra files in here you need to clear out first of all, and after that, having APCs remote from their areas is generally not an acceptable thing to do and you have no true reason to do it either. I'll give it a more proper look-through once you've fixed these things.

**Comment by BBBBAface** [comment]
> You've got extra files in here you need to clear out first of all, and after that, having APCs remote from their areas is generally not an acceptable thing to do and you have no true reason to do it either. I'll give it a more proper look-through once you've fixed these things.

my bad, those issues are fixed now

**Comment by GuiltyNeko** [comment]
I'll do a proper check tomorrow. For now, because I'll ask later if you aren't, make sure your decals are squashed, IE, you don't use two individual corner decals on one tile when you could use a single decal that looks identical.

**Review by GuiltyNeko — APPROVED** [review]
Looks good to me, I'd like a maptainer to peep it.

**Pull request closed without merging**
