### PR TITLE
removes an injustice

### PR DESCRIPTION
**Pull request by TJatPBnJ**
## About The Pull Request
Hotdogs don't need ketchup to craft anymore.

## Why It's Good For The Game
Hotdogs do not need ketchup and should not need ketchup.

## Changelog
:cl:
balance: Hotdogs no longer require ketchup to craft
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
Replace it with mustard

**Comment by TJatPBnJ** [comment]
if you want msutard on your hotdog you can put it on the hotdog

**Comment by SuperNovaa41** [comment]
these are my demands

**Comment by TJatPBnJ** [comment]
@SuperNovaa41 ok i did it merge it now please

**Comment by TJatPBnJ** [comment]
wait hold on

**Comment by TJatPBnJ** [comment]
alright NOW you can do it

**Comment by SuperNovaa41** [comment]
Not going to merge this until https://github.com/Jackriip/Voidcrew-LRP/pull/33 is merged, because this PR isn't worth fixing after the fact

**Comment by SuperNovaa41** [comment]
ok cool now modularize it

**Comment by SuperNovaa41** [comment]
OK

**Pull request closed without merging**
