### PR TITLE
Phalanx Chapel Decoration

### PR DESCRIPTION
**Pull request by shelteredfreak**
## About The Pull Request

Magical originally made this chapel because I was his friend and a chaplain main on TG, so I thought I would spice up the chapel. It looked so boring, needed touching up.

Phalanx Chapel

Small touches, not much besides adding a lesser smoke spell book and a nexus (fluff). 
## Why It's Good For The Game

Ship look good, make player happy, yes?

## Changelog
:cl:
add: Some new floors and decals to the Phalanx's Chapel.
/:cl:

### CODE REVIEW

**Comment by shelteredfreak** [comment]
ah fun, errors I do NOT know how to fix. yikes.

**Comment by dwasint** [comment]
phalanx's cargo seems to have var edited areas thats whats causing this error, should just have to replace the cargo area with a fresh copy

**Comment by dwasint** [comment]
This should be fixed though already? when was the last time you pulled the repo for editing?

**Comment by shelteredfreak** [comment]
> This should be fixed though already? when was the last time you pulled the repo for editing?

its been pulled fairly recently, and I've been keeping it updated. Not sure.

**Comment by shelteredfreak** [comment]
Not sure what the fix was, but surely making them the same area cant hurt....

**Pull request merged**
