### PR TITLE
Moves around piping on the scrapper-b, adds a couple useful things it was missing

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
Pipes. Wires. Enzyme. Flour. Empty machine frames. A missing air alarm. An RPD. One less sci-drobe, one more robodrobe. That's it. That's all. Also please stop putting devices under things that take up so much of a tile. A vent underneath a SMES? Really? Oh and one of the air tanks was set to the wrong layer. It's not anymore.

## Why It's Good For The Game
God I hate the piping on this ship, also cooking is good, now you can do more of it on this ship.

## Changelog
:cl:
tweak: The Scrapper-B has had its piping moved around to be more sensible, as well as receiving some extra cooking supplies and some needed miscellaneous equipment such as a rapid piping device.
/:cl:

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
Also, the airlock on this ship is MASSIVE, and an absolute nightmare to use. Can I just replace it with a few tiny fans and call it good?

**Comment by dwasint** [comment]
Airlocks are really shitty with this slow atmos, so feel free to replace it with tiny fans if you want to

**Comment by GuiltyNeko** [comment]
Huzzah, tiny fans. Oh wait. There's two other airlocks.

**Comment by GuiltyNeko** [comment]
THERE. Only one other airlock, but I got it too. All donezo.

**Pull request merged**
