### PR TITLE
Adds the Phalanx

### PR DESCRIPTION
**Pull request by magicaltheonething**
## About The Pull Request
Adds the Phalanx-Class Super Battlecruiser, its main purpose is to be NT's Twinkleshire. NT has only like two ships, if their faction is supposed to be as major as they are i'd figure itll be best to have a ship that can actually survive the round without getting curb stomped by the Syndicate and KOS ships
phalanxarea
phalanxnoarea

NT really needs a Capital ship of sorts, the Syndicate has the Twinkleshire, SolGov has the Rigourex or whatever its called, NT has nothing. I Believe adding this will benefit NT's Faction heavily.
## Changelog
:cl:
add: Adds NT-C_phalanx.json in _maps/configs
add: Adds phalanx.dmm in _maps/shuttles/shiptest/voidcrew

/:cl:

### CODE REVIEW

**Comment by theta006** [comment]
seccie venders and not NT venders

**Comment by Jackriip** [comment]
Can you replace half those weapon vendors with the solgov ones?

As for the captain, he likely won't start with any weapon vouchers. If the sec lockers contain them it's no big deal, but if not could you provide him with a locker that either has a weapon voucher or a weapon?

Could you also give the captain a commander ERT suit / storage unit?

Awesome work

**Comment by Jackriip** [comment]
Also could you lower the prince to match the twinkleshine?

**Comment by bsolomon9** [comment]
Ship looks good to go, my only grievance is that the pipes tend to go through walls and while this wont break anything, it is bad practice as the pipe cant be seen or accessed easily by players or mappers.

**Pull request merged**
