### PR TITLE
Make The Starfury (Twinkleshine) Buyable

### PR DESCRIPTION
**Pull request by Striketester**
This updates some job names (to fit the syndicate) and makes it able to be bought for 950 Meta Coins.
Nothing More Needs To Be Said...........

### CODE REVIEW

**Comment by rye-rice** [comment]
Word of advice, theres a reason why twinkleshine is admin only, and one of the obvious ones is that its full of nuke op gear, It will be overpowered no matter what.

**Comment by rye-rice** [comment]
And the correct name is twinkleshine, don't worry.

**Comment by Jackriip** [comment]
We're going to wait on this until we can get an NT ship of equivalent value / power. Then we will make them both automatically hostile to each other for ship battles

**Comment by Jackriip** [comment]
Closing this for now until we have added in factions to the rules / code, and the rest of the equivalent NT and syndicate ships

**Pull request closed without merging**
