### PR TITLE
Tartarus Edits, Adds a 9mm ammo disk to courage/Tartarus

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Basically a mirror of #[118](https://github.com/Jackriip/Voidcrew-LRP/pull/118). Hopefully works this time around.

## Changelog
:cl:
aadd: adds 9mm ammo disks (copy-paste)
tweak: HoS starts with vouchers, adds a mining vendor board to Hyena-class, other misc. edits
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
ugh, my mistake-- sorry!

**Comment by dwasint** [comment]
Okay i can approve the map changes, I'd ask that you modularize the custom lockers though

**Comment by githubuser4141** [comment]
> Okay i can approve the map changes, I'd ask that you modularize the custom lockers though

Put them in a misc file in /voidcrew, is that enough?

**Comment by dwasint** [comment]
Test Merged

**Comment by githubuser4141** [comment]
forgot to update the .dme's like a dingus :banghead::banghead::banghead:

**Comment by dwasint** [comment]
Hasn't been any glaring issues gonna merge this now

**Pull request merged**
